;;; cus-load.el --- automatically extracted custom dependencies
;;
;;; Code:

(put 'gnus-article-washing 'custom-loads '(gnus-art))
(put 'avoid 'custom-loads '(avoid))
(put 'vhdl-testbench 'custom-loads '(vhdl-mode))
(put 'perl 'custom-loads '(perl-mode))
(put 'crisp 'custom-loads '(crisp))
(put 'emerge 'custom-loads '(emerge))
(put 'tildify 'custom-loads '(tildify))
(put 'gnus-summary-marks 'custom-loads '(gnus-sum gnus))
(put 'cperl-indentation-details 'custom-loads '(cperl-mode))
(put 'gametree 'custom-loads '(gametree))
(put 'remember 'custom-loads '(remember))
(put 'hardware 'custom-loads '(battery))
(put 'unix 'custom-loads '(proced rlogin shell))
(put 'fringe 'custom-loads '(fringe))
(put 'time-stamp 'custom-loads '(time-stamp))
(put 'PostScript 'custom-loads '(ps-mode))
(put 'eudc-ph 'custom-loads '(eudc-vars))
(put 'spam-spamoracle 'custom-loads '(spam))
(put 'proced 'custom-loads '(proced))
(put 'erc-identd 'custom-loads '(erc-identd))
(put 'table 'custom-loads '(table))
(put 'erc-server-hooks 'custom-loads '(erc))
(put 'url-file 'custom-loads '(url-cache url-cookie url-vars))
(put 'gnus-score 'custom-loads '(gnus))
(put 'gnus-threading 'custom-loads '(gnus-sum))
(put 'bookmark 'custom-loads '(man bookmark))
(put 'allout-widgets-developer 'custom-loads '(allout-widgets))
(put 'vhdl-style 'custom-loads '(vhdl-mode))
(put 'SQL 'custom-loads '(sql))
(put 'ruby 'custom-loads '(ruby-mode))
(put 'viper-hooks 'custom-loads '(viper-init))
(put 'nroff 'custom-loads '(nroff-mode))
(put 'eshell-mode 'custom-loads '(esh-mode))
(put 'org-export-pdf 'custom-loads '(org-latex))
(put 'gnus-server 'custom-loads '(gnus-srvr gnus gnus-int nnheader))
(put 'archive 'custom-loads '(arc-mode))
(put 'url-mime 'custom-loads '(url-vars))
(put 'landmark 'custom-loads '(landmark))
(put 'multi-isearch 'custom-loads '("misearch"))
(put 'table-hooks 'custom-loads '(table))
(put 'paren-showing 'custom-loads '(paren))
(put 'ielm 'custom-loads '(ielm))
(put 'debug 'custom-loads '(debug))
(put 'hippie-expand 'custom-loads '(hippie-exp))
(put 'ps-print-face 'custom-loads '(ps-print))
(put 'reftex-viewing-cross-references 'custom-loads '(reftex-vars))
(put 'smtpmail 'custom-loads '(smtpmail))
(put 'imenu 'custom-loads '(imenu "imenu"))
(put 'org-sparse-trees 'custom-loads '(org))
(put 'gnus-topic 'custom-loads '(gnus-topic))
(put 'gnus-group-various 'custom-loads '(gnus-group gnus-start gnus))
(put 'gnus-asynchronous 'custom-loads '(gnus-async))
(put 'change-log 'custom-loads '(add-log))
(put 'idlwave-misc 'custom-loads '(idlwave))
(put 'generic-x 'custom-loads '(generic-x))
(put 'uce 'custom-loads '(uce))
(put 'games 'custom-loads '(5x5 bruce bubbles decipher dunnet fortune gametree gomoku handwrite hanoi landmark mpuz pong solitaire spook tetris yow))
(put 'makefile 'custom-loads '(make-mode))
(put 'bubbles 'custom-loads '(bubbles))
(put 'development 'custom-loads '(cus-edit))
(put 'undo 'custom-loads '(simple))
(put 'eshell-banner 'custom-loads '(em-banner))
(put 'srecode 'custom-loads '("document" "cpp" "expandproto" "fields" "insert" "map" "mode" "srt-mode"))
(put 'org-habit 'custom-loads '(org-habit))
(put 'viper-mouse 'custom-loads '(viper-mous))
(put 'ediff-diff 'custom-loads '(ediff-diff))
(put 'whitespace-faces 'custom-loads '(faces))
(put 'srecode-cpp 'custom-loads '("cpp"))
(put 'mail-abbrev 'custom-loads '(mailabbrev))
(put 'ido 'custom-loads '(ido))
(put 'vhdl-sequential-process 'custom-loads '(vhdl-mode))
(put 'rmail-headers 'custom-loads '(rmail undigest))
(put 'nnmail-duplicate 'custom-loads '(nnmail))
(put 'f90 'custom-loads '(f90))
(put 'tpu 'custom-loads '("tpu-extras" tpu-edt))
(put 'tramp 'custom-loads '(tramp tramp-gvfs tramp-sh tramp-cache tramp-smb))
(put 'newsticker-headline-processing 'custom-loads '(newst-backend))
(put 'abbrev 'custom-loads '(abbrev dabbrev files expand hippie-exp quickurl))
(put 'sieve 'custom-loads '(sieve-mode sieve))
(put 'prolog-inferior 'custom-loads '(prolog))
(put 'org-edit-structure 'custom-loads '(org org-src))
(put 'rcirc 'custom-loads '(rcirc))
(put 'dired-keys 'custom-loads '(dired-x))
(put 'dns-mode 'custom-loads '(dns-mode))
(put 'org-export-general 'custom-loads '(org-exp org-exp-blocks))
(put 'checkdoc 'custom-loads '(checkdoc))
(put 'gnus-summary-choose 'custom-loads '(gnus-sum))
(put 'feedmail-misc 'custom-loads '(feedmail))
(put 'gomoku 'custom-loads '(gomoku))
(put 'installation 'custom-loads '("startup"))
(put 'gdb-non-stop 'custom-loads '(gdb-mi))
(put 'cperl 'custom-loads '(cperl-mode))
(put 'visual-line 'custom-loads '(simple))
(put 'ffap 'custom-loads '(ffap))
(put 'vhdl-project 'custom-loads '(vhdl-mode))
(put 'ediff-hook 'custom-loads '(ediff-init ediff-mult))
(put 'url-gateway 'custom-loads '(url-gw))
(put 'gnus-article-headers 'custom-loads '(gnus-art gnus-sum gnus-fun))
(put 'next-error 'custom-loads '(simple))
(put 'ebnf-production 'custom-loads '(ebnf2ps))
(put 'tmm 'custom-loads '(tmm))
(put 'ebnf-shape 'custom-loads '(ebnf2ps))
(put 'message-various 'custom-loads '(message))
(put 'fortune-signature 'custom-loads '(fortune))
(put 'gnus-group-listing 'custom-loads '(gnus-group))
(put 'font-selection 'custom-loads '(faces))
(put 'org-progress 'custom-loads '(org-clock org org-habit))
(put 'mouse-sel 'custom-loads '(mouse-sel))
(put 'two-column 'custom-loads '(two-column))
(put 'languages 'custom-loads '(ps-mode sql ada-mode antlr-mode asm-mode cus-edit cfengine cperl-mode css-mode dcl-mode delphi f90 fortran hideshow icon idlwave info-look js ld-script m4-mode meta-mode modula2 nxml-mode octave-mod pascal perl-mode prolog python rng-valid ruby-mode sgml-mode sh-script sieve simula smie tcl vera-mode verilog-mode vhdl-mode))
(put 'eudc-bbdb 'custom-loads '(eudc-vars))
(put 'tls 'custom-loads '(tls))
(put 'log-edit 'custom-loads '(log-edit))
(put 'f90-indent 'custom-loads '(f90))
(put 'faces 'custom-loads '(faces cus-edit cwarn dired facemenu font-lock frame gnus hi-lock hilit-chg message paren proced ps-print rcirc rst speedbar wid-edit woman))
(put 'ls-lisp 'custom-loads '(ls-lisp))
(put 'eshell-module 'custom-loads '(esh-module))
(put 'ps-print-printer 'custom-loads '(lpr ps-print))
(put 'ange-ftp 'custom-loads '(ange-ftp))
(put 'org-agenda-time-grid 'custom-loads '(org-agenda))
(put 'org-bbdb-anniversaries 'custom-loads '(org-bbdb))
(put 'emulations 'custom-loads '(crisp cua-base edt tpu-edt vip viper))
(put 'align 'custom-loads '(align))
(put 'org-link-store 'custom-loads '(org org-gnus))
(put 'makeinfo 'custom-loads '(makeinfo))
(put 'idlwave-completion 'custom-loads '(idlwave))
(put 'nnmail 'custom-loads '(nnmail))
(put 'gnus-group-icons 'custom-loads '(gnus-group))
(put 'ps-print-background 'custom-loads '(ps-print))
(put 'flyspell 'custom-loads '(flyspell))
(put 'gnus-summary-various 'custom-loads '(gnus-sum))
(put 'erc-stamp 'custom-loads '(erc-stamp))
(put 'dframe 'custom-loads '(dframe))
(put 'programming 'custom-loads '(cus-edit))
(put 'org-completion 'custom-loads '(org))
(put 'lisp 'custom-loads '(advice bytecomp checkdoc cust-print "lisp" edebug eldoc elp lisp-mode ert simple find-func gmm-utils ielm inf-lisp "cl-indent" shadow pp re-builder unsafep scheme testcover trace warnings xscheme))
(put 'term 'custom-loads '(terminal term))
(put 'customize 'custom-loads '(cus-edit custom wid-edit))
(put 'gnus-visual 'custom-loads '(gnus-art gnus-gravatar gnus smiley))
(put 'lisp-mnt 'custom-loads '(lisp-mnt))
(put 'sh-indentation 'custom-loads '(sh-script))
(put 'nndiary 'custom-loads '(nndiary))
(put 'sort 'custom-loads '(sort))
(put 'menu 'custom-loads '(menu-bar faces tmm))
(put 'octave 'custom-loads '(octave-mod octave-inf))
(put 'ebnf-optimization 'custom-loads '(ebnf2ps))
(put 'erc-scripts 'custom-loads '(erc))
(put 'linum 'custom-loads '(linum))
(put 'bibtex 'custom-loads '(bibtex bibtex-style))
(put 'vhdl-align 'custom-loads '(vhdl-mode))
(put 'gnus-extract 'custom-loads '(gnus-uu gnus))
(put 'erc-services 'custom-loads '(erc-services))
(put 'eshell-basic 'custom-loads '(em-basic))
(put 'electricity 'custom-loads '(electric))
(put 'spam 'custom-loads '(spam))
(put 'hide-ifdef 'custom-loads '(hideif))
(put 'gnus-summary-pick 'custom-loads '(gnus-salt))
(put 'erc-mode-line-and-header 'custom-loads '(erc))
(put 'shell-directories 'custom-loads '(shell))
(put 'image-dired 'custom-loads '(image-dired))
(put 'view 'custom-loads '(calendar view files))
(put 'ldap 'custom-loads '(ldap))
(put 'ps-print-color 'custom-loads '(ps-print))
(put 'mail-extr 'custom-loads '(mail-extr))
(put 'fortran-indent 'custom-loads '(fortran))
(put 'gnus-registry 'custom-loads '(gnus-registry))
(put 'data 'custom-loads '(arc-mode jka-cmpr-hook conf-mode dns-mode doc-view epg-config forms generic-x hexl remember saveplace snmp-mode sort tar-mode time-stamp timeclock))
(put 'woman 'custom-loads '(woman))
(put 'newsticker-treeview 'custom-loads '(newst-treeview))
(put 'tex 'custom-loads '(bibtex tex-mode reftex-vars))
(put 'trace 'custom-loads '(trace))
(put 'lazy-highlight 'custom-loads '("isearch" ispell "replace"))
(put 'completion 'custom-loads '(completion simple minibuffer iswitchb))
(put 'calendar-tex 'custom-loads '(cal-tex))
(put 'ogonek 'custom-loads '(ogonek))
(put 'erc-control-characters 'custom-loads '(erc-goodies))
(put 'multimedia 'custom-loads '(doc-view image image-dired mm-decode mpc thumbs))
(put 'erc-capab 'custom-loads '(erc-capab))
(put 'ps-print-headers 'custom-loads '(ps-print))
(put 'testcover 'custom-loads '(testcover))
(put 'ediff-merge 'custom-loads '(ediff-init ediff-merg))
(put 'gnus-gravatar 'custom-loads '(gnus-gravatar))
(put 'message-mail 'custom-loads '(message))
(put 'bib 'custom-loads '(bib-mode))
(put 'ebnf-syntactic 'custom-loads '(ebnf2ps))
(put 'comint-completion 'custom-loads '(comint))
(put 'solitaire 'custom-loads '(solitaire))
(put 'wdired 'custom-loads '(wdired))
(put 'tcl 'custom-loads '(tcl))
(put 'cperl-affected-by-hairy 'custom-loads '(cperl-mode))
(put 'widgets 'custom-loads '(tree-widget wid-browse wid-edit))
(put 'mpuz 'custom-loads '(mpuz))
(put 'info-lookup 'custom-loads '(info-look))
(put 'archive-7z 'custom-loads '(arc-mode))
(put 'org-export-docbook 'custom-loads '(org-docbook))
(put 'cedet 'custom-loads '(cedet-cscope cedet-global cedet-idutils))
(put 'log-view 'custom-loads '(log-view))
(put 'proced-faces 'custom-loads '(proced))
(put 'compression 'custom-loads '(jka-cmpr-hook))
(put 'gnus-files 'custom-loads '(gnus nnmail))
(put 'follow 'custom-loads '(follow))
(put 'org-table-import-export 'custom-loads '(org-table))
(put 'erc-faces 'custom-loads '(erc-goodies erc erc-button erc-capab erc-match erc-stamp))
(put 'gnus-outlook-deuglify 'custom-loads '(deuglify))
(put 'calendar-faces 'custom-loads '(calendar diary-lib))
(put 'tar 'custom-loads '(tar-mode))
(put 'gud 'custom-loads '(gdb-mi gud tooltip))
(put 'yow 'custom-loads '(yow))
(put 'ispell 'custom-loads '(flyspell ispell))
(put 'vhdl-print 'custom-loads '(vhdl-mode))
(put 'msb 'custom-loads '(msb))
(put 'org-agenda-skip 'custom-loads '(org-agenda org))
(put 'nxml 'custom-loads '(nxml-mode nxml-outln rng-valid))
(put 'rmail-summary 'custom-loads '(rmail rmailsum))
(put 'emacsbug 'custom-loads '(emacsbug))
(put 'erc-autojoin 'custom-loads '(erc-join))
(put 'custom-browse 'custom-loads '(cus-edit))
(put 'eshell-smart 'custom-loads '(em-smart))
(put 'icalendar 'custom-loads '(icalendar))
(put 'pcl-cvs 'custom-loads '(pcvs-defs pcvs-info pcvs pcvs-parse cvs-status log-edit log-view))
(put 'tempo 'custom-loads '(tempo))
(put 'eudc 'custom-loads '(eudc-vars))
(put 'gnus-windows 'custom-loads '(gnus-win))
(put 'org-agenda-line-format 'custom-loads '(org-agenda))
(put 'w32 'custom-loads '(w32-vars))
(put 'find-file 'custom-loads '(files find-file))
(put 'socks 'custom-loads '(socks))
(put 'scheme 'custom-loads '(cmuscheme scheme))
(put 'editing 'custom-loads '(simple cus-edit electric "fill" "indent" faces "paragraphs"))
(put 'apropos 'custom-loads '(apropos))
(put 'org-agenda-search-view 'custom-loads '(org-agenda))
(put 'dired-faces 'custom-loads '(dired))
(put 'gnus-score-expire 'custom-loads '(gnus-kill gnus-score))
(put 'dunnet 'custom-loads '(dunnet))
(put 'eshell-proc 'custom-loads '(esh-proc))
(put 'semanticdb 'custom-loads '("db-file" "db-ebrowse" "db"))
(put 'asm 'custom-loads '(asm-mode))
(put 'highlight-changes 'custom-loads '(hilit-chg))
(put 'Buffer-menu 'custom-loads '("buff-menu"))
(put 'gnus-art 'custom-loads '(gnus-art gnus-html))
(put 'gnus-score-various 'custom-loads '(gnus-score gnus))
(put 'viper 'custom-loads '(viper-init viper-ex viper viper-mous viper-keym viper-macs viper-util))
(put 'mpc 'custom-loads '(mpc))
(put 'recentf 'custom-loads '(recentf))
(put 'electric-help 'custom-loads '(ehelp))
(put 'ebrowse-member 'custom-loads '(ebrowse))
(put 'vhdl-template 'custom-loads '(vhdl-mode))
(put 'htmlfontify 'custom-loads '(htmlfontify))
(put 'eshell-dirs 'custom-loads '(em-dirs))
(put 'terminals 'custom-loads '(terminal))
(put 'ebnf-repeat 'custom-loads '(ebnf2ps))
(put 'message-headers 'custom-loads '(message))
(put 'executable 'custom-loads '(executable))
(put 'delphi 'custom-loads '(delphi))
(put 'find-function 'custom-loads '(find-func))
(put 'org-entities 'custom-loads '(org-entities))
(put 'gnus-article-treat 'custom-loads '(gnus-art))
(put 'netrc 'custom-loads '(netrc))
(put 'gnus-start 'custom-loads '(gnus-int gnus-start gnus gnus-group gnus-util nnheader))
(put 'viper-ex 'custom-loads '(viper-ex))
(put 'erc-track 'custom-loads '(erc-track))
(put 'gnus-sync 'custom-loads '(gnus-sync))
(put 'reftex-label-support 'custom-loads '(reftex-vars))
(put 'refer 'custom-loads '(refer))
(put 'reftex-optimizations-for-large-documents 'custom-loads '(reftex-vars))
(put 'eshell-ls 'custom-loads '(em-ls))
(put 'nnmail-expire 'custom-loads '(nnmail))
(put 'warnings 'custom-loads '(warnings))
(put 'auto-save 'custom-loads '(files "startup"))
(put 'erc-sound 'custom-loads '(erc-sound))
(put 'org-export-icalendar 'custom-loads '(org-icalendar))
(put 'ld-script 'custom-loads '(ld-script))
(put 'message-forwarding 'custom-loads '(message))
(put 'environment 'custom-loads '(dired cus-edit "dos-vars" "startup" faces minibuffer "paths" w32-vars))
(put 'etags 'custom-loads '(etags speedbar))
(put 'org-tags 'custom-loads '(org org-faces))
(put 'allout-encryption 'custom-loads '(allout))
(put 'eshell-var 'custom-loads '(esh-var))
(put 'gnus-various 'custom-loads '(gnus-util gnus-sum gnus))
(put 'pcmpl-cvs 'custom-loads '(pcmpl-cvs))
(put 'dos-fns 'custom-loads '("dos-vars"))
(put 'gmm 'custom-loads '(gmm-utils))
(put 'gnus-cite 'custom-loads '(gnus-cite gnus-msg))
(put 'rst-toc 'custom-loads '(rst))
(put 'grep 'custom-loads '(grep))
(put 'calendar 'custom-loads '(appt calendar cal-x cal-china cal-dst cal-html solar cal-tex diary-lib holidays icalendar lunar midnight org todo-mode))
(put 'emacs 'custom-loads '(cus-edit ebnf2ps))
(put 'org-mobile 'custom-loads '(org-mobile))
(put 'supercite-hooks 'custom-loads '(supercite))
(put 'shr 'custom-loads '(shr shr-color))
(put 'allout-widgets 'custom-loads '(allout-widgets))
(put 'eshell-io 'custom-loads '(esh-io))
(put 'eshell-cmpl 'custom-loads '(em-cmpl))
(put 'icon 'custom-loads '(icon))
(put 'gnus-charset 'custom-loads '(gnus gnus-group gnus-sum))
(put 'org-bibtex 'custom-loads '(org-bibtex))
(put 'viper-highlighting 'custom-loads '(viper-init))
(put 'paragraphs 'custom-loads '("paragraphs"))
(put 'wisent 'custom-loads '("wisent" "comp"))
(put 'gnus-article-highlight 'custom-loads '(gnus-art))
(put 'ediff 'custom-loads '(ediff-init ediff-diff ediff-mult ediff-ptch ediff ediff-wind))
(put 'reftex-defining-label-environments 'custom-loads '(reftex-vars))
(put 'speedbar-faces 'custom-loads '(speedbar vhdl-mode))
(put 'sieve-manage 'custom-loads '(sieve-manage))
(put 'pong 'custom-loads '(pong))
(put 'erc-ignore 'custom-loads '(erc))
(put 'org-babel 'custom-loads '(ob-js ob-lisp org ob-lob ob ob-tangle ob-scheme ob-sh ob-exp ob-plantuml org-src))
(put 'verilog-mode-auto 'custom-loads '(verilog-mode))
(put 'org-inlinetask 'custom-loads '(org-inlinetask))
(put 'org-publish 'custom-loads '(org-publish))
(put 'epa-faces 'custom-loads '(epa))
(put 'tex-view 'custom-loads '(tex-mode))
(put 'dirtrack 'custom-loads '(dirtrack))
(put 'erc-ezbounce 'custom-loads '(erc-ezbounce))
(put 'bibtex-autokey 'custom-loads '(bibtex))
(put 'news 'custom-loads '(binhex canlock gnus message mm-decode spam spam-report supercite uudecode))
(put 'pop3 'custom-loads '(pop3))
(put 'verilog-mode-actions 'custom-loads '(verilog-mode))
(put 'org-table-editing 'custom-loads '(org-table org))
(put 'nnmail-files 'custom-loads '(nnmail))
(put 'ses 'custom-loads '(ses))
(put 'epa-file 'custom-loads '(epa-file epa-hook))
(put 'sendmail 'custom-loads '(sendmail))
(put 'gnus-format 'custom-loads '(gnus-spec))
(put 'timeclock 'custom-loads '(timeclock))
(put 'newsticker-miscellaneous 'custom-loads '(newst-backend))
(put 'LaTeX 'custom-loads '(reftex-vars))
(put 'vhdl 'custom-loads '(vhdl-mode))
(put 'erc-autoaway 'custom-loads '(erc-autoaway))
(put 'gnus-group-visual 'custom-loads '(gnus-group gnus))
(put 'verilog-mode 'custom-loads '(verilog-mode))
(put 'org-startup 'custom-loads '(org))
(put 'eshell-pred 'custom-loads '(em-pred))
(put 'bytecomp 'custom-loads '(bytecomp))
(put 'picture 'custom-loads '(picture))
(put 'archive-zoo 'custom-loads '(arc-mode))
(put 'mouse 'custom-loads '(artist avoid goto-addr faces mouse mouse-sel mwheel msb strokes tooltip))
(put 'prolog 'custom-loads '(prolog))
(put 'save-place 'custom-loads '(saveplace))
(put 'org-freemind 'custom-loads '(org-freemind))
(put 'gnus-article-signature 'custom-loads '(gnus-art))
(put 'diary 'custom-loads '(calendar diary-lib cal-hebrew))
(put 'recentf-filters 'custom-loads '(recentf))
(put 'basic-faces 'custom-loads '(faces button frame fringe "isearch" shadowfile tooltip))
(put 'rst 'custom-loads '(rst))
(put 'gnus-bookmark 'custom-loads '(gnus-bookmark))
(put 'org-agenda-windows 'custom-loads '(org-agenda org))
(put 'BibTeX 'custom-loads '(bibtex))
(put 'snmp 'custom-loads '(snmp-mode))
(put 'gnus-summary-exit 'custom-loads '(gnus-sum gnus))
(put 'prolog-indentation 'custom-loads '(prolog))
(put 'i18n 'custom-loads '(ccl double iso-ascii latin1-disp cus-edit ogonek url-vars))
(put 'ps-print-zebra 'custom-loads '(ps-print))
(put 'gnus-fun 'custom-loads '(gnus-fun))
(put 'inferior-lisp 'custom-loads '(inf-lisp))
(put 'spam-spamassassin 'custom-loads '(spam))
(put 'maint 'custom-loads '(elint emacsbug gulp lisp-mnt))
(put 'prolog-other 'custom-loads '(prolog))
(put 'calendar-html 'custom-loads '(cal-html))
(put 'gnus-sieve 'custom-loads '(gnus-sieve))
(put 'org-refile 'custom-loads '(org))
(put 'spam-crm114 'custom-loads '(spam))
(put 'spam-stat 'custom-loads '(spam-stat))
(put 'gnus-group-select 'custom-loads '(gnus-sum gnus gnus-group))
(put 'keyboard 'custom-loads '(chistory mule keypad kmacro type-break))
(put 'eldoc 'custom-loads '(eldoc))
(put 'eshell-cmd 'custom-loads '(esh-cmd))
(put 'hanoi 'custom-loads '(hanoi))
(put 'org-appearance 'custom-loads '(org-faces org))
(put 'org-agenda-sorting 'custom-loads '(org-agenda))
(put 'modula2 'custom-loads '(modula2))
(put 'woman-formatting 'custom-loads '(woman))
(put 'gdb 'custom-loads '(gdb-mi))
(put 'org-agenda-startup 'custom-loads '(org-agenda))
(put 'supercite-frames 'custom-loads '(supercite))
(put 'rmail 'custom-loads '(rmail "paths" rmailmm rmail-spam-filter))
(put 'erc-notify 'custom-loads '(erc-notify))
(put 'allout-keybindings 'custom-loads '(allout))
(put 'spam-bsfilter 'custom-loads '(spam))
(put 'eshell-hist 'custom-loads '(em-hist))
(put 'man 'custom-loads '(man))
(put 'strokes 'custom-loads '(strokes))
(put 'dired-mark 'custom-loads '(dired))
(put 'eieio 'custom-loads '(chart eieio-custom))
(put 'pcmpl-unix 'custom-loads '(pcmpl-unix))
(put 'eshell-util 'custom-loads '(esh-util))
(put 'emacs-lock 'custom-loads '(emacs-lock))
(put 'reftex 'custom-loads '(reftex-vars))
(put 'lpr 'custom-loads '(lpr))
(put 'org-link-follow 'custom-loads '(org org-mhe))
(put 'cursor 'custom-loads '(frame))
(put 'ada 'custom-loads '(ada-xref ada-mode))
(put 'archive-zip 'custom-loads '(arc-mode))
(put 'erc-query 'custom-loads '(erc))
(put 'hi-lock 'custom-loads '(hi-lock))
(put 'vhdl-model 'custom-loads '(vhdl-mode))
(put 'rmail-retrieve 'custom-loads '(rmail))
(put 'erc-hooks 'custom-loads '(erc erc-netsplit))
(put 'gnus-article-saving 'custom-loads '(gnus gnus-art))
(put 'eshell-unix 'custom-loads '(em-unix))
(put 'font-lock-faces 'custom-loads '(font-lock))
(put 'idlwave-shell-highlighting-and-faces 'custom-loads '(idlw-shell))
(put 'calendar-hooks 'custom-loads '(cal-x calendar))
(put 'erc-paranoia 'custom-loads '(erc))
(put 'mail-source 'custom-loads '(mail-source nndiary pop3))
(put 'nxml-faces 'custom-loads '(nxml-mode nxml-outln))
(put 'speedbar-vc 'custom-loads '(speedbar))
(put 'org-mac-flagged-mail 'custom-loads '(org-mac-message))
(put 'refbib 'custom-loads '(refbib))
(put 'spam-report 'custom-loads '(spam-report))
(put 'hl-line 'custom-loads '(hl-line))
(put 'rmail-spam-filter 'custom-loads '(rmail-spam-filter))
(put 'gnus-article 'custom-loads '(gnus-art gnus-cite))
(put 'iso-ascii 'custom-loads '(iso-ascii))
(put 'gnus-exit 'custom-loads '(gnus-group gnus))
(put 'org-archive 'custom-loads '(org org-archive org-exp))
(put 'password 'custom-loads '(password-cache))
(put 'gnus-score-kill 'custom-loads '(gnus gnus-kill))
(put 'url-cookie 'custom-loads '(url-cookie))
(put 'newsticker-ticker 'custom-loads '(newst-ticker))
(put 'winner 'custom-loads '(winner))
(put 'erc-dcc 'custom-loads '(erc-dcc erc-xdcc))
(put 'org-agenda-daily/weekly 'custom-loads '(org-agenda org-faces org))
(put 'soap-client 'custom-loads '(soap-client))
(put 'mm-url 'custom-loads '(mm-url))
(put 'eshell-rebind 'custom-loads '(em-rebind))
(put 'custom-faces 'custom-loads '(cus-edit eieio-custom))
(put 'supercite-attr 'custom-loads '(supercite))
(put 'desktop 'custom-loads '(desktop))
(put 'rmail-edit 'custom-loads '(rmailedit))
(put 'gnus-score-files 'custom-loads '(gnus-score gnus))
(put 'spook 'custom-loads '(spook))
(put 'mule 'custom-loads '(mule "mule-cmds" descr-text kkc latexenc select))
(put 'kmacro 'custom-loads '(edmacro kmacro))
(put 'rmail-reply 'custom-loads '(rmail))
(put 'fill 'custom-loads '("fill" align simple newcomment longlines refill "paragraphs"))
(put 'vhdl-menu 'custom-loads '(vhdl-mode))
(put 'abbrev-mode 'custom-loads '(abbrev mailabbrev))
(put 'newsticker-reader 'custom-loads '(newst-reader newst-plainview newst-treeview))
(put 'org-table-settings 'custom-loads '(org-table))
(put 'rst-faces 'custom-loads '(rst))
(put 'reftex-miscellaneous-configurations 'custom-loads '(reftex-vars))
(put 'message-faces 'custom-loads '(message))
(put 'uniquify 'custom-loads '(uniquify))
(put 'vhdl-highlight-faces 'custom-loads '(vhdl-mode))
(put 'double 'custom-loads '(double))
(put 'ebrowse-faces 'custom-loads '(ebrowse))
(put 'eshell-alias 'custom-loads '(em-alias))
(put 'newsticker-faces 'custom-loads '(newst-plainview newst-reader))
(put 'dabbrev 'custom-loads '(dabbrev))
(put 'nnmail-split 'custom-loads '(nndiary nnmail))
(put 'feedmail 'custom-loads '(feedmail))
(put 'mime 'custom-loads '(mailcap mm-bodies mm-util mm-encode rfc1843 smime))
(put 'vhdl-comment 'custom-loads '(vhdl-mode))
(put 'bruce 'custom-loads '(bruce))
(put 'idlwave-abbrev-and-indent-action 'custom-loads '(idlwave))
(put 'jit-lock 'custom-loads '(jit-lock))
(put 'display-time 'custom-loads '(time))
(put 'org-keywords 'custom-loads '(org))
(put 'data-debug 'custom-loads '(data-debug))
(put 'shadow 'custom-loads '(shadowfile))
(put 'file-cache 'custom-loads '(filecache))
(put 'convenience 'custom-loads '("buff-menu" cus-edit autoinsert autorevert bs completion files cua-base dabbrev emacs-lock ffap filecache filesets follow hippie-exp hl-line ibuffer ido imenu iswitchb kmacro linum master abbrev org-protocol repeat reveal ruler-mode speedbar vcursor simple whitespace windmove))
(put 'ezimage 'custom-loads '(ezimage))
(put 'reftex-table-of-contents-browser 'custom-loads '(reftex-vars))
(put 'pulse 'custom-loads '(pulse))
(put 'remote-compile 'custom-loads '(rcompile))
(put 'semantic-symref 'custom-loads '("list"))
(put 'cust-print 'custom-loads '(cust-print))
(put 'prolog-keyboard 'custom-loads '(prolog))
(put 'semantic 'custom-loads '("mru-bookmark" "mode" "c" semantic "edit" "format" "grammar" "util-modes" "idle" "imenu" "lex" "lex-spp" "grep" "list" "db" "senator" "wisent"))
(put 'relax-ng 'custom-loads '(rng-valid rng-nxml rng-loc))
(put 'auto-revert 'custom-loads '(autorevert))
(put 'paren-matching 'custom-loads '(simple paren))
(put 'editing-basics 'custom-loads '(files cua-base simple))
(put 'spam-bogofilter 'custom-loads '(spam))
(put 'erc-speedbar 'custom-loads '(erc-speedbar))
(put 'smerge 'custom-loads '(smerge-mode))
(put 'woman-interface 'custom-loads '(woman))
(put 'idlwave-shell-general-setup 'custom-loads '(idlw-shell idlwave))
(put 'fancy-splash-screen 'custom-loads '("startup"))
(put 'tooltip 'custom-loads '(gud tooltip))
(put 'erc-truncate 'custom-loads '(erc-truncate))
(put 'gnus-article-emphasis 'custom-loads '(gnus-art))
(put 'processes 'custom-loads '(sql ansi-color comint compile executable cus-edit flyspell grep gud metamail pcomplete proced rcompile rlogin shell socks term))
(put 'pascal 'custom-loads '(pascal))
(put 'network 'custom-loads '(gssapi))
(put 'gnus-cache 'custom-loads '(gnus-cache gnus))
(put 'org-footnote 'custom-loads '(org-footnote))
(put 'nnmail-procmail 'custom-loads '(nnmail))
(put 'ps-print-font 'custom-loads '(ps-print ps-mule))
(put 'mode-line-faces 'custom-loads '(time faces))
(put 'plstore 'custom-loads '(plstore))
(put 'forms 'custom-loads '(forms))
(put 'help-at-pt 'custom-loads '(help-at-pt))
(put 'gnus-demon 'custom-loads '(gnus-demon))
(put 'org-export-tables 'custom-loads '(org-exp org-html))
(put 'custom-buffer 'custom-loads '(cus-edit cus-theme))
(put 'ps-print 'custom-loads '(ps-print))
(put 'custom-magic-faces 'custom-loads '(cus-edit))
(put 'compare-windows 'custom-loads '(compare-w))
(put 'fortran 'custom-loads '(fortran))
(put 'org-mew 'custom-loads '(org-mew))
(put 'elint 'custom-loads '(elint))
(put 'org-latex 'custom-loads '(org))
(put 'ebnf2ps 'custom-loads '(ebnf2ps))
(put 'allout-developer 'custom-loads '(allout))
(put 'ediff-mult 'custom-loads '(ediff-mult))
(put 'message-sending 'custom-loads '(message))
(put 'info 'custom-loads '(info))
(put 'spam-ifile 'custom-loads '(spam))
(put 'org-table 'custom-loads '(org org-table))
(put 'cmuscheme 'custom-loads '(cmuscheme))
(put 'org-link 'custom-loads '(org org-ctags org-mac-message org-mew org-wl))
(put 'jka-compr 'custom-loads '(jka-cmpr-hook jka-compr))
(put 'which-func 'custom-loads '(which-func))
(put 'printing 'custom-loads '(printing))
(put 'sgml 'custom-loads '(sgml-mode))
(put 'mailalias 'custom-loads '(mailalias))
(put 'erc-server 'custom-loads '(erc-backend))
(put 'display 'custom-loads '(face-remap "characters" simple))
(put 'gnus-group-new 'custom-loads '(gnus-start))
(put 'conf 'custom-loads '(conf-mode))
(put 'midnight 'custom-loads '(midnight))
(put 'bs-appearance 'custom-loads '(bs))
(put 'archive-arc 'custom-loads '(arc-mode))
(put 'flymake 'custom-loads '(flymake))
(put 'allout 'custom-loads '(allout allout-widgets))
(put 'eshell-term 'custom-loads '(em-term))
(put 'comm 'custom-loads '(ange-ftp browse-url dig eudc-vars goto-addr gravatar ldap net-utils netrc tls tramp url-vars xesam))
(put 'ebnf-non-terminal 'custom-loads '(ebnf2ps))
(put 'rlogin 'custom-loads '(rlogin))
(put 'isearchb 'custom-loads '(isearchb))
(put 'font-lock-highlighting-faces 'custom-loads '(vera-mode verilog-mode))
(put 'ert 'custom-loads '(ert))
(put 'tree-widget 'custom-loads '(tree-widget))
(put 'mail-hist 'custom-loads '(mail-hist))
(put 'gnus-summary-mail 'custom-loads '(gnus-sum))
(put 'todo 'custom-loads '(todo-mode))
(put 'indent 'custom-loads '("indent"))
(put 'eshell-prompt 'custom-loads '(em-prompt))
(put 'smie 'custom-loads '(smie))
(put 'gnus-score-default 'custom-loads '(gnus-sum gnus-score))
(put 'gnus-agent 'custom-loads '(gnus gnus-agent))
(put 'sh-script 'custom-loads '(sh-script))
(put 'server 'custom-loads '(server))
(put 'erc 'custom-loads '(erc-autoaway erc-join erc erc-button erc-capab erc-goodies erc-dcc erc-ezbounce erc-fill erc-ibuffer erc-identd erc-log erc-match erc-netsplit erc-networks erc-notify erc-page erc-pcomplete erc-replace erc-services erc-sound erc-speedbar erc-stamp erc-track erc-truncate))
(put 'mime-display 'custom-loads '(flow-fill mm-decode mm-view))
(put 'org-wl 'custom-loads '(org-wl))
(put 'gnus-duplicate 'custom-loads '(gnus-dup))
(put 'org-export-latex 'custom-loads '(org-beamer org-latex org org-exp))
(put 'comment 'custom-loads '(newcomment))
(put 'org-ctags 'custom-loads '(org-ctags))
(put 'org-feed 'custom-loads '(org-feed))
(put 'hexl 'custom-loads '(hexl))
(put 'idlwave-shell-command-setup 'custom-loads '(idlw-shell))
(put 'nnmail-various 'custom-loads '(nnmail))
(put 'nnmail-retrieve 'custom-loads '(nnmail))
(put 'vhdl-port 'custom-loads '(vhdl-mode))
(put 'windmove 'custom-loads '(windmove))
(put 'gnus-summary-maneuvering 'custom-loads '(gnus-sum))
(put 'epg 'custom-loads '(epa epg-config))
(put 'org-export 'custom-loads '(org-ascii org-docbook org-exp org-html org-icalendar org-latex org-taskjuggler))
(put 'ruler-mode 'custom-loads '(ruler-mode))
(put 'decipher 'custom-loads '(decipher))
(put 'feedmail-debug 'custom-loads '(feedmail))
(put 'epa 'custom-loads '(epa epa-hook))
(put 'newsticker-plainview-hooks 'custom-loads '(newst-plainview))
(put 'widget-documentation 'custom-loads '(wid-edit))
(put 'message 'custom-loads '(footnote message mml mml-sec "startup"))
(put 'starttls 'custom-loads '(starttls))
(put 'gnus-score-decay 'custom-loads '(gnus-score))
(put 'semantic-imenu 'custom-loads '("imenu"))
(put 'archive-lzh 'custom-loads '(arc-mode))
(put 'vhdl-compose 'custom-loads '(vhdl-mode))
(put 'scrolling 'custom-loads '("window"))
(put 'gnus-article-mime 'custom-loads '(gnus-sum gnus-art mm-uu))
(put 'gnus-score-adapt 'custom-loads '(gnus-score gnus))
(put 'font-lock 'custom-loads '(font-lock font-core hi-lock jit-lock prolog))
(put 'org-properties 'custom-loads '(org))
(put 'dired 'custom-loads '(files dired dired-aux dired-x find-dired ls-lisp wdired))
(put 'rst-adjust 'custom-loads '(rst))
(put 'reveal 'custom-loads '(reveal))
(put 'paren-showing-faces 'custom-loads '(paren))
(put 'idlwave-external-programs 'custom-loads '(idlwave))
(put 'smime 'custom-loads '(smime))
(put 'gnus-summary 'custom-loads '(gnus-sum gnus))
(put 'wp 'custom-loads '(bib-mode delim-col ebnf2ps enriched lpr nroff-mode outline picture printing ps-print refbib refer rng-valid rst table cus-edit "text-mode" tildify view))
(put 'quickurl 'custom-loads '(quickurl))
(put 'PostScript-edit 'custom-loads '(ps-mode))
(put 'gnus-edit-form 'custom-loads '(gnus-eform))
(put 'lisp-shadow 'custom-loads '(shadow))
(put 'org-attach 'custom-loads '(org-attach))
(put 'latin1-display 'custom-loads '(latin1-disp))
(put 'senator 'custom-loads '("senator"))
(put 'gnus-newsrc 'custom-loads '(gnus-start))
(put 'elp 'custom-loads '(elp))
(put 'tex-file 'custom-loads '(tex-mode))
(put 'erc-fill 'custom-loads '(erc-fill))
(put 'org-remember 'custom-loads '(org org-remember))
(put 'message-news 'custom-loads '(message))
(put 'widget-button 'custom-loads '(wid-edit))
(put 'dired-x 'custom-loads '(dired-x))
(put 'binhex 'custom-loads '(binhex))
(put 'org-capture 'custom-loads '(org-capture))
(put 'org-cycle 'custom-loads '(org))
(put 'vc 'custom-loads '(log-edit vc vc-annotate vc-arch vc-bzr vc-dispatcher vc-hooks vc-cvs vc-dir vc-git vc-hg vc-mtn vc-rcs vc-sccs vc-svn files))
(put 'vc-bzr 'custom-loads '(vc-bzr))
(put 'advice 'custom-loads '(advice))
(put 'hideshow 'custom-loads '(hideshow))
(put 'eshell-glob 'custom-loads '(em-glob))
(put 'locate 'custom-loads '(locate))
(put 'ebnf-terminal 'custom-loads '(ebnf2ps))
(put 'type-break 'custom-loads '(type-break))
(put 'org-faces 'custom-loads '(org-faces org org-footnote org-habit))
(put 'octave-inferior 'custom-loads '(octave-mod octave-inf))
(put 'elide-head 'custom-loads '(elide-head))
(put 'debugger 'custom-loads '(debug))
(put 'handwrite 'custom-loads '(handwrite))
(put 'org-export-translation 'custom-loads '(org-latex org-exp org))
(put 'erc-quit-and-part 'custom-loads '(erc))
(put 'doc-view 'custom-loads '(doc-view))
(put 'erc-netsplit 'custom-loads '(erc-netsplit))
(put 'fortran-comment 'custom-loads '(fortran))
(put 'eudc-ldap 'custom-loads '(eudc-vars))
(put 'mspools 'custom-loads '(mspools))
(put 'eshell-arg 'custom-loads '(esh-arg))
(put 'gnus-diary 'custom-loads '(gnus-diary nndiary))
(put 'meta-font 'custom-loads '(meta-mode))
(put 'org-infojs 'custom-loads '(org-jsinfo))
(put 'reftex-making-and-inserting-labels 'custom-loads '(reftex-vars))
(put 'matching 'custom-loads '(bookmark "replace" completion ffap imenu "isearch" simple))
(put 'artist 'custom-loads '(artist))
(put 'newsticker-hooks 'custom-loads '(newst-backend newst-plainview))
(put 'sh 'custom-loads '(sh-script))
(put 'ediff-ptch 'custom-loads '(ediff-ptch))
(put '5x5 'custom-loads '(5x5))
(put 'vhdl-speedbar 'custom-loads '(vhdl-mode))
(put 'killing 'custom-loads '(simple))
(put 'erc-display 'custom-loads '(erc erc-goodies))
(put 'vhdl-header 'custom-loads '(vhdl-mode))
(put 'feedmail-spray 'custom-loads '(feedmail))
(put 'smiley 'custom-loads '(smiley))
(put 'speedbar 'custom-loads '("sb" speedbar sb-image))
(put 'gdb-buffers 'custom-loads '(gdb-mi))
(put 'org-agenda-column-view 'custom-loads '(org-agenda))
(put 'semantic-faces 'custom-loads '("complete" "include" "mode" "util-modes" "senator" "fields"))
(put 'pcmpl-gnu 'custom-loads '(pcmpl-gnu))
(put 'pages 'custom-loads '(page-ext))
(put 'terminal 'custom-loads '(terminal))
(put 'ibuffer 'custom-loads '(ibuffer ibuf-ext))
(put 'widget-faces 'custom-loads '(wid-edit))
(put 'ebnf-displacement 'custom-loads '(ebnf2ps))
(put 'gnus-extract-archive 'custom-loads '(gnus-uu))
(put 'vhdl-compile 'custom-loads '(vhdl-mode))
(put 'org-beamer 'custom-loads '(org-beamer))
(put 'pp 'custom-loads '(pp))
(put 'ps-print-vertical 'custom-loads '(ps-print))
(put 'ediff-window 'custom-loads '(ediff-wind ediff-help))
(put 'vera 'custom-loads '(vera-mode))
(put 'message-insertion 'custom-loads '(message))
(put 'gulp 'custom-loads '(gulp))
(put 'help 'custom-loads '(apropos cus-edit ehelp faces help-at-pt help-fns help-mode help info info-look man help-macro tooltip tutorial woman))
(put 'idlwave 'custom-loads '(idlwave idlw-help idlw-shell))
(put 'edt 'custom-loads '(edt))
(put 'diff-mode 'custom-loads '(diff-mode))
(put 'hashcash 'custom-loads '(hashcash))
(put 'lisp-indent 'custom-loads '("cl-indent"))
(put 'org-agenda-custom-commands 'custom-loads '(org-agenda))
(put 'ede 'custom-loads '(ede "locate" "make" "base" "simple" "project-am"))
(put 'metamail 'custom-loads '(metamail))
(put 'viper-misc 'custom-loads '(viper viper-init viper-cmd))
(put 'paren-blinking 'custom-loads '(simple))
(put 'calendar-dst 'custom-loads '(cal-dst))
(put 'org-id 'custom-loads '(org org-id))
(put 'mime-security 'custom-loads '(gnus-art mm-decode mm-encode mml-smime mml2015))
(put 'org-export-ascii 'custom-loads '(org-ascii))
(put 'gnus-group-foreign 'custom-loads '(gnus-group gnus-msg))
(put 'viper-search 'custom-loads '(viper-init))
(put 'ps-print-miscellany 'custom-loads '(ps-bdf ps-print))
(put 'cperl-help-system 'custom-loads '(cperl-mode))
(put 'vhdl-misc 'custom-loads '(vhdl-mode))
(put 'calculator 'custom-loads '(calculator))
(put 'cfengine 'custom-loads '(cfengine))
(put 'eshell 'custom-loads '(esh-arg eshell esh-cmd esh-ext esh-io esh-mode esh-module esh-opt esh-proc esh-util esh-var))
(put 'org-indent 'custom-loads '(org-indent))
(put 'erc-match 'custom-loads '(erc-match))
(put 'erc-button 'custom-loads '(erc-button))
(put 'gnus-summary-visual 'custom-loads '(gnus-sum))
(put 'simula 'custom-loads '(simula))
(put 'supercite 'custom-loads '(supercite))
(put 'reftex-citation-support 'custom-loads '(reftex-vars))
(put 'org-agenda-export 'custom-loads '(org-agenda))
(put 'ebnf-except 'custom-loads '(ebnf2ps))
(put 'gnus-group 'custom-loads '(gnus gnus-group gnus-topic))
(put 'tex-run 'custom-loads '(tex-mode))
(put 'org-export-html 'custom-loads '(org-agenda org-html org-exp org-jsinfo))
(put 'copyright 'custom-loads '(copyright))
(put 'gnus-dribble-file 'custom-loads '(gnus-start))
(put 'message-interface 'custom-loads '(message))
(put 'antlr 'custom-loads '(antlr-mode))
(put 'imap 'custom-loads '(imap))
(put 'filesets 'custom-loads '(filesets))
(put 'org-protocol 'custom-loads '(org-protocol))
(put 'js 'custom-loads '(js))
(put 'gnus-summary-tree 'custom-loads '(gnus-salt))
(put 'org-export-taskjuggler 'custom-loads '(org-taskjuggler))
(put 'org-agenda-todo-list 'custom-loads '(org-agenda))
(put 'nnmairix 'custom-loads '(nnmairix))
(put 'widget-browse 'custom-loads '(wid-browse))
(put 'cperl-faces 'custom-loads '(cperl-mode))
(put 'image 'custom-loads '(iimage image-mode image-file image))
(put 'initialization 'custom-loads '("startup"))
(put 'backup 'custom-loads '(files vc-hooks))
(put 'm4 'custom-loads '(m4-mode))
(put 'vhdl-highlight 'custom-loads '(vhdl-mode))
(put 'cwarn 'custom-loads '(cwarn))
(put 'appt 'custom-loads '(appt))
(put 'enriched 'custom-loads '(enriched))
(put 'rst-faces-defaults 'custom-loads '(rst))
(put 'vip 'custom-loads '(vip))
(put 'internal 'custom-loads '(cus-edit))
(put 'outlines 'custom-loads '(allout org outline))
(put 'project-am 'custom-loads '("project-am"))
(put 'hi-lock-faces 'custom-loads '(hi-lock))
(put 'ediff-vers 'custom-loads '(ediff-vers))
(put 'dnd 'custom-loads '(dnd))
(put 'woman-faces 'custom-loads '(woman))
(put 'org-plain-lists 'custom-loads '(org-list))
(put 'PostScript-interaction 'custom-loads '(ps-mode))
(put 'gnus-start-server 'custom-loads '(gnus-start))
(put 'browse-url 'custom-loads '(browse-url))
(put 'mode-line 'custom-loads '(time faces))
(put 'gnus 'custom-loads '(auth-source gnus gnus-art gnus-async gnus-bookmark gnus-delay gnus-demon gnus-diary gnus-dup gnus-eform gnus-uu deuglify gnus-sieve gnus-sync gnus-undo gnus-win mail-source mm-url nnir nnmail nnmairix nntp spam-stat))
(put 'reftex-index-support 'custom-loads '(reftex-vars))
(put 'battery 'custom-loads '(battery))
(put 'gnus-article-hiding 'custom-loads '(gnus-cite gnus-art gnus-sum))
(put 'iimage 'custom-loads '(iimage))
(put 'minibuffer 'custom-loads '(minibuffer rfn-eshadow icomplete simple savehist))
(put 'gnus-undo 'custom-loads '(gnus-undo))
(put 'canlock 'custom-loads '(canlock))
(put 'document 'custom-loads '("document"))
(put 'gravatar 'custom-loads '(gravatar))
(put 'ff 'custom-loads '(find-file))
(put 'url-cache 'custom-loads '(url-vars url-cache))
(put 'gnus-extract-view 'custom-loads '(gnus-sum gnus-uu))
(put 'url-hairy 'custom-loads '(url-vars url-util))
(put 'pcomplete 'custom-loads '(em-cmpl pcmpl-cvs pcmpl-gnu pcmpl-linux pcomplete))
(put 'tools 'custom-loads '("buff-menu" calculator add-log compare-w compile copyright diff diff-mode ebrowse ede ediff elide-head emerge etags flymake gdb-mi glasses grep gud make-mode pcvs-defs "project-am" rcompile semantic sieve smerge-mode soap-client speedbar srecode tempo tooltip vc which-func))
(put 'gnus-server-visual 'custom-loads '(gnus-srvr))
(put 'icomplete 'custom-loads '(icomplete))
(put 'prolog-font-lock 'custom-loads '(prolog))
(put 'ecomplete 'custom-loads '(ecomplete))
(put 'erc-ibuffer 'custom-loads '(erc-ibuffer))
(put 'eshell-script 'custom-loads '(em-script))
(put 'gnus-delay 'custom-loads '(gnus-delay))
(put 'tetris 'custom-loads '(tetris))
(put 'newsticker 'custom-loads '(newst-backend newst-reader newst-ticker))
(put 'facemenu 'custom-loads '(facemenu))
(put 'vc-hg 'custom-loads '(vc-hg))
(put 'gnus-summary-sort 'custom-loads '(gnus-sum))
(put 'nnmail-prepare 'custom-loads '(nnmail))
(put 'nntp 'custom-loads '(nntp))
(put 'reftex-finding-files 'custom-loads '(reftex-vars))
(put 'rcirc-faces 'custom-loads '(rcirc))
(put 'ps-print-horizontal 'custom-loads '(ps-print))
(put 'extensions 'custom-loads '(cust-print data-debug ede eldoc ido page-ext srecode time-stamp wid-edit xesam))
(put 'dig 'custom-loads '(dig net-utils))
(put 'rmail-files 'custom-loads '(rmail))
(put 'footnote 'custom-loads '(footnote))
(put 'frames 'custom-loads '(faces frame desktop ediff-wind "window" fringe imenu scroll-bar two-column))
(put 'applications 'custom-loads '(calc calculator calendar doc-view erc eshell cus-edit htmlfontify ispell mpc newst-backend package rcirc ses))
(put 'org-crypt 'custom-loads '(org-crypt))
(put 'erc-networks 'custom-loads '(erc-networks))
(put 'rmail-output 'custom-loads '(rmailout))
(put 'external 'custom-loads '(bib-mode browse-url locate man ebnf2ps cus-edit server))
(put 'bs 'custom-loads '(bs))
(put 'gnus-thread 'custom-loads '(gnus-sum gnus-group))
(put 'isearch 'custom-loads '("isearch" "misearch"))
(put 'uudecode 'custom-loads '(uudecode))
(put 'expand 'custom-loads '(expand))
(put 'reftex-referencing-labels 'custom-loads '(reftex-vars))
(put 'glasses 'custom-loads '(glasses))
(put 'iswitchb 'custom-loads '(isearchb iswitchb))
(put 'artist-text 'custom-loads '(artist))
(put 'org-table-calculation 'custom-loads '(org-table))
(put 'python 'custom-loads '(python))
(put 'reftex-fontification-configurations 'custom-loads '(reftex-vars))
(put 'ps-print-page 'custom-loads '(ps-print))
(put 'idlwave-code-formatting 'custom-loads '(idlwave))
(put 'org-agenda-match-view 'custom-loads '(org-agenda))
(put 'gnus-meta 'custom-loads '(gnus-util gnus))
(put 'url 'custom-loads '(url-vars url url-cookie url-gw url-history url-irc url-news url-queue))
(put 'ediff-highlighting 'custom-loads '(ediff-init))
(put 'shell 'custom-loads '(dirtrack shell terminal))
(put 'mairix 'custom-loads '(mairix))
(put 'postscript 'custom-loads '(ebnf2ps printing ps-print))
(put 'mailcap 'custom-loads '(mailcap))
(put 'mail 'custom-loads '(binhex simple time ecomplete emacsbug eudc-vars feedmail fortune gnus gnus-dired hashcash imap mail-utils mail-extr mail-hist "startup" mailalias mailclient mairix message metamail mm-decode mspools pop3 rmail sendmail shr sieve-manage smtpmail spam spam-report starttls supercite uce uudecode))
(put 'org-time 'custom-loads '(org org-timer))
(put 'idlwave-routine-info 'custom-loads '(idlwave))
(put 'windows 'custom-loads '("window" follow windmove winner))
(put 'erc-buffers 'custom-loads '(erc))
(put 'vcursor 'custom-loads '(vcursor))
(put 'feedmail-queue 'custom-loads '(feedmail))
(put 'xesam 'custom-loads '(xesam))
(put 'c-macro 'custom-loads '(cmacexp))
(put 'goto-address 'custom-loads '(goto-addr))
(put 'edebug 'custom-loads '(edebug))
(put 'vhdl-mode 'custom-loads '(vhdl-mode))
(put 'org 'custom-loads '(org org-attach ob org-capture org-pcomplete org-crypt org-entities org-exp org-feed org-footnote org-freemind org-id org-indent org-mobile org-mouse org-protocol org-publish org-remember))
(put 'files 'custom-loads '(files ange-ftp mule autoinsert autorevert cus-edit dired filecache latexenc plstore recentf shadowfile tramp uniquify))
(put 'x 'custom-loads '(x-dnd))
(put 'rmail-mime 'custom-loads '(rmailmm))
(put 'fortune 'custom-loads '(fortune))
(put 'cua 'custom-loads '(cua-base))
(put 'org-clocktable 'custom-loads '(org-clock))
(put 'url-history 'custom-loads '(url-history))
(put 'erc-spelling 'custom-loads '(erc-spelling))
(put 'newsticker-plainview 'custom-loads '(newst-plainview))
(put 'idlwave-documentation 'custom-loads '(idlwave))
(put 'idlwave-online-help 'custom-loads '(idlw-help))
(put 'ebnf-special 'custom-loads '(ebnf2ps))
(put 'gnutls 'custom-loads '(gnutls))
(put 'holidays 'custom-loads '(calendar holidays))
(put 'css 'custom-loads '(css-mode))
(put 'comint 'custom-loads '(comint))
(put 'c 'custom-loads '("cc-vars" cc-fonts "cc-guess" cmacexp cpp hideif "c"))
(put 'org-priorities 'custom-loads '(org))
(put 'feedmail-headers 'custom-loads '(feedmail))
(put 'message-buffers 'custom-loads '(message))
(put 'gnus-picon 'custom-loads '(gnus-art gnus-picon))
(put 'supercite-cite 'custom-loads '(supercite))
(put 'calendar-chinese 'custom-loads '(cal-china))
(put 'dcl 'custom-loads '(dcl-mode))
(put 'leim 'custom-loads '(quail))
(put 'savehist 'custom-loads '(savehist))
(put 'gnus-group-levels 'custom-loads '(gnus-start gnus gnus-group))
(put 'erc-pcomplete 'custom-loads '(erc-pcomplete))
(put 'org-mouse 'custom-loads '(org-mouse))
(put 'ebrowse-tree 'custom-loads '(ebrowse))
(put 'gnus-article-buttons 'custom-loads '(gnus-art))
(put 're-builder 'custom-loads '(re-builder))
(put 'newsticker-retrieval 'custom-loads '(newst-backend))
(put 'gnus-article-various 'custom-loads '(gnus-art gnus-sum))
(put 'columns 'custom-loads '(delim-col))
(put 'org-export-htmlize 'custom-loads '(org-html))
(put 'longlines 'custom-loads '(longlines))
(put 'eshell-ext 'custom-loads '(esh-ext))
(put 'gnus-extract-post 'custom-loads '(gnus-uu))
(put 'cperl-autoinsert-details 'custom-loads '(cperl-mode))
(put 'thumbs 'custom-loads '(thumbs))
(put 'auth-source 'custom-loads '(auth-source))
(put 'org-babel-tangle 'custom-loads '(ob-tangle))
(put 'auto-insert 'custom-loads '(autoinsert))
(put 'org-agenda 'custom-loads '(org-agenda org))
(put 'cpp 'custom-loads '(cpp))
(put 'verilog-mode-indent 'custom-loads '(verilog-mode))
(put 'xscheme 'custom-loads '(xscheme))
(put 'net-utils 'custom-loads '(net-utils gnutls))
(put 'ps-print-n-up 'custom-loads '(ps-print))
(put 'ebrowse 'custom-loads '(ebrowse))
(put 'custom-menu 'custom-loads '(cus-edit))
(put 'vhdl-naming 'custom-loads '(vhdl-mode))
(put 'cperl-speed 'custom-loads '(cperl-mode))
(put 'compilation 'custom-loads '(compile simple))
(put 'package 'custom-loads '(package-x package))
(put 'erc-page 'custom-loads '(erc-page))
(put 'erc-replace 'custom-loads '(erc-replace))
(put 'org-structure 'custom-loads '(org org-inlinetask org-list))
(put 'org-todo 'custom-loads '(org org-clock org-faces))
(put 'org-clock 'custom-loads '(org-agenda org-clock))
(put 'diff 'custom-loads '(diff diff-mode))
(put 'texinfo 'custom-loads '(informat "document" texinfo))
(put 'ansi-colors 'custom-loads '(ansi-color))
(put 'org-bbdb 'custom-loads '(org-bbdb))
(put 'chistory 'custom-loads '(chistory))
(put 'calc 'custom-loads '(calc))
(put 'nnir 'custom-loads '(nnir))
(put 'local 'custom-loads '(holidays))
(put 'docs 'custom-loads '(info makeinfo texinfo))
(put 'erc-log 'custom-loads '(erc-log))
(put 'whitespace 'custom-loads '(whitespace))
(put 'find-dired 'custom-loads '(find-dired))
(put 'gnus-message 'custom-loads '(gnus-msg gnus-draft gnus message))
(put 'gnus-summary-format 'custom-loads '(gnus-diary gnus gnus-sum))
(put 'semantic-modes 'custom-loads '("mru-bookmark"))
(put 'org-imenu-and-speedbar 'custom-loads '(org))
;; These are for handling :version.  We need to have a minimum of
;; information so `customize-changed-options' could do its job.

;; For groups we set `custom-version', `group-documentation' and
;; `custom-tag' (which are shown in the customize buffer), so we
;; don't have to load the file containing the group.

;; `custom-versions-load-alist' is an alist that has as car a version
;; number and as elts the files that have variables or faces that
;; contain that version. These files should be loaded before showing
;; the customization buffer that `customize-changed-options'
;; generates.

;; This macro is used so we don't modify the information about
;; variables and groups if it's already set. (We don't know when
;; cus-load.el is going to be loaded and at that time some of the
;; files might be loaded and some others might not).
(defmacro custom-put-if-not (symbol propname value)
  `(unless (get ,symbol ,propname)
     (put ,symbol ,propname ,value)))

(custom-put-if-not 'tildify 'custom-version "21.1")
(custom-put-if-not 'tildify 'group-documentation "Adding missing hard spaces or other text fragments into texts.")
(custom-put-if-not 'gametree 'custom-version "20.3")
(custom-put-if-not 'gametree 'group-documentation "Manage game analysis trees in Emacs.")
(custom-put-if-not 'table 'custom-version "22.1")
(custom-put-if-not 'table 'group-documentation "Text based table manipulation utilities.")
(custom-put-if-not 'table 'custom-tag "Table")
(custom-put-if-not 'SQL 'custom-version "20.4")
(custom-put-if-not 'SQL 'group-documentation "Running a SQL interpreter from within Emacs buffers.")
(custom-put-if-not 'multi-isearch 'custom-version "23.1")
(custom-put-if-not 'multi-isearch 'group-documentation "Using isearch to search through multiple buffers.")
(custom-put-if-not 'ps-print-face 'custom-version "20")
(custom-put-if-not 'ps-print-face 'group-documentation "Faces customization.")
(custom-put-if-not 'ps-print-face 'custom-tag "PS Faces")
(custom-put-if-not 'generic-x 'custom-version "20.3")
(custom-put-if-not 'generic-x 'group-documentation "A collection of generic modes.")
(custom-put-if-not 'ido 'custom-version "22.1")
(custom-put-if-not 'ido 'group-documentation "Switch between files using substrings.")
(custom-put-if-not 'tramp 'custom-version "22.1")
(custom-put-if-not 'tramp 'group-documentation "Edit remote files with a combination of rsh and rcp or similar programs.")
(custom-put-if-not 'sieve 'custom-version "22.1")
(custom-put-if-not 'sieve 'group-documentation "Manage sieve scripts.")
(custom-put-if-not 'rcirc 'custom-version "22.1")
(custom-put-if-not 'rcirc 'group-documentation "Simple IRC client.")
(custom-put-if-not 'checkdoc 'custom-version "20.3")
(custom-put-if-not 'checkdoc 'group-documentation "Support for doc string checking in Emacs Lisp.")
(custom-put-if-not 'gdb-non-stop 'custom-version "23.2")
(custom-put-if-not 'gdb-non-stop 'group-documentation "GDB non-stop debugging settings")
(custom-put-if-not 'cperl 'custom-version "20.3")
(custom-put-if-not 'cperl 'group-documentation "Major mode for editing Perl code.")
(custom-put-if-not 'visual-line 'custom-version "23.1")
(custom-put-if-not 'visual-line 'group-documentation "Editing based on visual lines.")
(custom-put-if-not 'ebnf-production 'custom-version "20")
(custom-put-if-not 'ebnf-production 'group-documentation "Production customization.")
(custom-put-if-not 'ebnf-production 'custom-tag "Production")
(custom-put-if-not 'ebnf-shape 'custom-version "20")
(custom-put-if-not 'ebnf-shape 'group-documentation "Shapes customization.")
(custom-put-if-not 'ebnf-shape 'custom-tag "Shape")
(custom-put-if-not 'log-edit 'custom-version "21.1")
(custom-put-if-not 'log-edit 'group-documentation "Major mode for editing RCS and CVS commit messages.")
(custom-put-if-not 'ls-lisp 'custom-version "21.1")
(custom-put-if-not 'ls-lisp 'group-documentation "Emulate the ls program completely in Emacs Lisp.")
(custom-put-if-not 'ps-print-printer 'custom-version "20")
(custom-put-if-not 'ps-print-printer 'group-documentation "Printer customization.")
(custom-put-if-not 'ps-print-printer 'custom-tag "Printer")
(custom-put-if-not 'align 'custom-version "21.1")
(custom-put-if-not 'align 'group-documentation "Align text to a specific column, by regexp.")
(custom-put-if-not 'ps-print-background 'custom-version "20")
(custom-put-if-not 'ps-print-background 'group-documentation "Background customization.")
(custom-put-if-not 'ps-print-background 'custom-tag "Background")
(custom-put-if-not 'nndiary 'custom-version "22.1")
(custom-put-if-not 'nndiary 'group-documentation "The Gnus Diary back end.")
(custom-put-if-not 'ebnf-optimization 'custom-version "20")
(custom-put-if-not 'ebnf-optimization 'group-documentation "Optimization customization.")
(custom-put-if-not 'ebnf-optimization 'custom-tag "Optimization")
(custom-put-if-not 'ldap 'custom-version "21.1")
(custom-put-if-not 'ldap 'group-documentation "Lightweight Directory Access Protocol.")
(custom-put-if-not 'ps-print-color 'custom-version "20")
(custom-put-if-not 'ps-print-color 'group-documentation "Color customization.")
(custom-put-if-not 'ps-print-color 'custom-tag "Color")
(custom-put-if-not 'gnus-registry 'custom-version "22.1")
(custom-put-if-not 'gnus-registry 'group-documentation "Article Registry.")
(custom-put-if-not 'ps-print-headers 'custom-version "20")
(custom-put-if-not 'ps-print-headers 'group-documentation "Headers & footers layout.")
(custom-put-if-not 'ps-print-headers 'custom-tag "Header & Footer")
(custom-put-if-not 'testcover 'custom-version "21.1")
(custom-put-if-not 'testcover 'group-documentation "Code-coverage tester.")
(custom-put-if-not 'ebnf-syntactic 'custom-version "20")
(custom-put-if-not 'ebnf-syntactic 'group-documentation "Syntactic customization.")
(custom-put-if-not 'ebnf-syntactic 'custom-tag "Syntactic")
(custom-put-if-not 'gnus-outlook-deuglify 'custom-version "22.1")
(custom-put-if-not 'gnus-outlook-deuglify 'group-documentation "Deuglify articles generated by broken user agents like MS Outlook (Express).")
(custom-put-if-not 'pcl-cvs 'custom-version "21.1")
(custom-put-if-not 'pcl-cvs 'group-documentation "Special support for the CVS versioning system.")
(custom-put-if-not 'eudc 'custom-version "21.1")
(custom-put-if-not 'eudc 'group-documentation "Emacs Unified Directory Client.")
(custom-put-if-not 'w32 'custom-version "22.1")
(custom-put-if-not 'w32 'group-documentation "MS-Windows specific features.")
(custom-put-if-not 'socks 'custom-version "22.2")
(custom-put-if-not 'socks 'group-documentation "SOCKS Support")
(custom-put-if-not 'recentf 'custom-version "21.1")
(custom-put-if-not 'recentf 'group-documentation "Maintain a menu of recently opened files.")
(custom-put-if-not 'electric-help 'custom-version "21.1")
(custom-put-if-not 'electric-help 'group-documentation "Electric help facility.")
(custom-put-if-not 'ebnf-repeat 'custom-version "20")
(custom-put-if-not 'ebnf-repeat 'group-documentation "Repeat customization.")
(custom-put-if-not 'ebnf-repeat 'custom-tag "Repeat")
(custom-put-if-not 'delphi 'custom-version "21.1")
(custom-put-if-not 'delphi 'group-documentation "Major mode for editing Delphi source in Emacs.")
(custom-put-if-not 'gnus-sync 'custom-version "24.1")
(custom-put-if-not 'gnus-sync 'group-documentation "The Gnus synchronization facility.")
(custom-put-if-not 'warnings 'custom-version "22.1")
(custom-put-if-not 'warnings 'group-documentation "Log and display warnings.")
(custom-put-if-not 'gmm 'custom-version "22.1")
(custom-put-if-not 'gmm 'group-documentation "Utility functions for Gnus, Message and MML.")
(custom-put-if-not 'rst-toc 'custom-version "21.1")
(custom-put-if-not 'rst-toc 'group-documentation "Settings for reStructuredText table of contents.")
(custom-put-if-not 'gnus-charset 'custom-version "21.1")
(custom-put-if-not 'gnus-charset 'group-documentation "Group character set issues.")
(custom-put-if-not 'epa-faces 'custom-version "23.1")
(custom-put-if-not 'epa-faces 'group-documentation "Faces for epa-mode.")
(custom-put-if-not 'ses 'custom-version "21.1")
(custom-put-if-not 'ses 'group-documentation "Simple Emacs Spreadsheet.")
(custom-put-if-not 'epa-file 'custom-version "23.1")
(custom-put-if-not 'epa-file 'group-documentation "The EasyPG Assistant hooks for transparent file encryption")
(custom-put-if-not 'verilog-mode 'custom-version "22.2")
(custom-put-if-not 'verilog-mode 'group-documentation "Facilitates easy editing of Verilog source text.")
(custom-put-if-not 'rst 'custom-version "23.1")
(custom-put-if-not 'rst 'group-documentation "Support for reStructuredText documents.")
(custom-put-if-not 'snmp 'custom-version "20.4")
(custom-put-if-not 'snmp 'group-documentation "Mode for editing SNMP MIB files.")
(custom-put-if-not 'ps-print-zebra 'custom-version "20")
(custom-put-if-not 'ps-print-zebra 'group-documentation "Zebra customization.")
(custom-put-if-not 'ps-print-zebra 'custom-tag "Zebra")
(custom-put-if-not 'inferior-lisp 'custom-version "22.1")
(custom-put-if-not 'inferior-lisp 'group-documentation "Run an outside Lisp in an Emacs buffer.")
(custom-put-if-not 'spam-stat 'custom-version "22.1")
(custom-put-if-not 'spam-stat 'group-documentation "Statistical spam detection for Emacs.
Use the functions to build a dictionary of words and their statistical
distribution in spam and non-spam mails.  Then use a function to determine
whether a buffer contains spam or not.")
(custom-put-if-not 'gdb 'custom-version "23.2")
(custom-put-if-not 'gdb 'group-documentation "GDB graphical interface")
(custom-put-if-not 'emacs-lock 'custom-version "24.1")
(custom-put-if-not 'emacs-lock 'group-documentation "Emacs-Lock mode.")
(custom-put-if-not 'mail-source 'custom-version "21.1")
(custom-put-if-not 'mail-source 'group-documentation "The mail-fetching library.")
(custom-put-if-not 'kmacro 'custom-version "22.1")
(custom-put-if-not 'kmacro 'group-documentation "Simplified keyboard macro user interface.")
(custom-put-if-not 'rst-faces 'custom-version "21.1")
(custom-put-if-not 'rst-faces 'group-documentation "Faces used in Rst Mode.")
(custom-put-if-not 'master 'custom-version "22.1")
(custom-put-if-not 'master 'group-documentation "Support for master/slave relationships between buffers.")
(custom-put-if-not 'jit-lock 'custom-version "21.1")
(custom-put-if-not 'jit-lock 'group-documentation "Font Lock support mode to fontify just-in-time.")
(custom-put-if-not 'fancy-splash-screen 'custom-version "21.1")
(custom-put-if-not 'fancy-splash-screen 'group-documentation "Fancy splash screen when Emacs starts.")
(custom-put-if-not 'ps-print-font 'custom-version "20")
(custom-put-if-not 'ps-print-font 'group-documentation "Fonts customization.")
(custom-put-if-not 'ps-print-font 'custom-tag "Font")
(custom-put-if-not 'mode-line-faces 'custom-version "22.1")
(custom-put-if-not 'mode-line-faces 'group-documentation "Faces used in the mode line.")
(custom-put-if-not 'plstore 'custom-version "24.1")
(custom-put-if-not 'plstore 'group-documentation "Searchable, partially encrypted, persistent plist store")
(custom-put-if-not 'help-at-pt 'custom-version "22.1")
(custom-put-if-not 'help-at-pt 'group-documentation "Features for displaying local help.")
(custom-put-if-not 'ps-print 'custom-version "20")
(custom-put-if-not 'ps-print 'group-documentation "PostScript generator for Emacs.")
(custom-put-if-not 'ebnf2ps 'custom-version "20")
(custom-put-if-not 'ebnf2ps 'group-documentation "Translate an EBNF to a syntactic chart on PostScript.")
(custom-put-if-not 'printing 'custom-version "22.1")
(custom-put-if-not 'printing 'group-documentation "Printing Utilities group.")
(custom-put-if-not 'printing 'custom-tag "Printing Utilities")
(custom-put-if-not 'conf 'custom-version "22.1")
(custom-put-if-not 'conf 'group-documentation "Configuration files.")
(custom-put-if-not 'midnight 'custom-version "20.3")
(custom-put-if-not 'midnight 'group-documentation "Run something every day at midnight.")
(custom-put-if-not 'flymake 'custom-version "23.1")
(custom-put-if-not 'flymake 'group-documentation "A universal on-the-fly syntax checker.")
(custom-put-if-not 'ebnf-non-terminal 'custom-version "20")
(custom-put-if-not 'ebnf-non-terminal 'group-documentation "Non-Terminal customization.")
(custom-put-if-not 'ebnf-non-terminal 'custom-tag "Non-Terminal")
(custom-put-if-not 'tree-widget 'custom-version "22.1")
(custom-put-if-not 'tree-widget 'group-documentation "Customization support for the Tree Widget library.")
(custom-put-if-not 'todo 'custom-version "21.1")
(custom-put-if-not 'todo 'group-documentation "Maintain a list of todo items.")
(custom-put-if-not 'mime-display 'custom-version "21.1")
(custom-put-if-not 'mime-display 'group-documentation "Display of MIME in mail and news articles.")
(custom-put-if-not 'comment 'custom-version "21.1")
(custom-put-if-not 'comment 'group-documentation "Indenting and filling of comments.")
(custom-put-if-not 'windmove 'custom-version "21.1")
(custom-put-if-not 'windmove 'group-documentation "Directional selection of windows in a frame.")
(custom-put-if-not 'epg 'custom-version "23.1")
(custom-put-if-not 'epg 'group-documentation "The EasyPG library.")
(custom-put-if-not 'ruler-mode 'custom-version "22.1")
(custom-put-if-not 'ruler-mode 'group-documentation "Display a ruler in the header line.")
(custom-put-if-not 'epa 'custom-version "23.1")
(custom-put-if-not 'epa 'group-documentation "The EasyPG Assistant")
(custom-put-if-not 'starttls 'custom-version "21.1")
(custom-put-if-not 'starttls 'group-documentation "Support for `Transport Layer Security' protocol.")
(custom-put-if-not 'scrolling 'custom-version "21.1")
(custom-put-if-not 'scrolling 'group-documentation "Scrolling windows.")
(custom-put-if-not 'rst-adjust 'custom-version "21.1")
(custom-put-if-not 'rst-adjust 'group-documentation "Settings for adjustment and cycling of section title decorations.")
(custom-put-if-not 'paren-showing-faces 'custom-version "22.1")
(custom-put-if-not 'paren-showing-faces 'group-documentation "Group for faces of Show Paren mode.")
(custom-put-if-not 'quickurl 'custom-version "21.1")
(custom-put-if-not 'quickurl 'group-documentation "Insert a URL based on text at point in buffer.")
(custom-put-if-not 'vc-bzr 'custom-version "22.2")
(custom-put-if-not 'vc-bzr 'group-documentation "VC bzr backend.")
(custom-put-if-not 'ebnf-terminal 'custom-version "20")
(custom-put-if-not 'ebnf-terminal 'group-documentation "Terminal customization.")
(custom-put-if-not 'ebnf-terminal 'custom-tag "Terminal")
(custom-put-if-not 'elide-head 'custom-version "21.1")
(custom-put-if-not 'elide-head 'group-documentation "Eliding copyright headers and the like in source files.")
(custom-put-if-not 'doc-view 'custom-version "22.2")
(custom-put-if-not 'doc-view 'group-documentation "In-buffer viewer for PDF, PostScript and DVI files.")
(custom-put-if-not 'gnus-diary 'custom-version "22.1")
(custom-put-if-not 'gnus-diary 'group-documentation "Utilities on top of the nndiary back end for Gnus.")
(custom-put-if-not 'gdb-buffers 'custom-version "23.2")
(custom-put-if-not 'gdb-buffers 'group-documentation "GDB buffers")
(custom-put-if-not 'ibuffer 'custom-version "22.1")
(custom-put-if-not 'ibuffer 'group-documentation "An advanced replacement for `buffer-menu'.

Ibuffer allows you to operate on buffers in a manner much like Dired.
Operations include sorting, marking by regular expression, and
the ability to filter the displayed buffers by various criteria.")
(custom-put-if-not 'ebnf-displacement 'custom-version "20")
(custom-put-if-not 'ebnf-displacement 'group-documentation "Displacement customization.")
(custom-put-if-not 'ebnf-displacement 'custom-tag "Displacement")
(custom-put-if-not 'ps-print-vertical 'custom-version "20")
(custom-put-if-not 'ps-print-vertical 'group-documentation "Vertical page layout.")
(custom-put-if-not 'ps-print-vertical 'custom-tag "Vertical")
(custom-put-if-not 'vera 'custom-version "22.2")
(custom-put-if-not 'vera 'group-documentation "Customizations for Vera Mode.")
(custom-put-if-not 'rst-compile 'custom-version "21.1")
(custom-put-if-not 'rst-compile 'group-documentation "Settings for support of conversion of reStructuredText
document with \\[rst-compile].")
(custom-put-if-not 'diff-mode 'custom-version "21.1")
(custom-put-if-not 'diff-mode 'group-documentation "Major mode for viewing/editing diffs.")
(custom-put-if-not 'ps-print-miscellany 'custom-version "20")
(custom-put-if-not 'ps-print-miscellany 'group-documentation "Miscellany customization.")
(custom-put-if-not 'ps-print-miscellany 'custom-tag "Miscellany")
(custom-put-if-not 'calculator 'custom-version "21.1")
(custom-put-if-not 'calculator 'group-documentation "Simple Emacs calculator.")
(custom-put-if-not 'eshell 'custom-version "21.1")
(custom-put-if-not 'eshell 'group-documentation "A command shell implemented entirely in Emacs Lisp.
It invokes no external processes beyond those requested by the
user, and is intended to be a functional replacement for command
shells such as bash, zsh, rc, 4dos.")
(custom-put-if-not 'eshell 'custom-tag "The Emacs shell")
(custom-put-if-not 'ebnf-except 'custom-version "20")
(custom-put-if-not 'ebnf-except 'group-documentation "Except customization.")
(custom-put-if-not 'ebnf-except 'custom-tag "Except")
(custom-put-if-not 'imap 'custom-version "21.1")
(custom-put-if-not 'imap 'group-documentation "Low-level IMAP issues.")
(custom-put-if-not 'filesets 'custom-version "22.1")
(custom-put-if-not 'filesets 'group-documentation "The fileset swapper.")
(custom-put-if-not 'org-protocol 'custom-version "22.1")
(custom-put-if-not 'org-protocol 'group-documentation "Intercept calls from emacsclient to trigger custom actions.

This is done by advising `server-visit-files' to scan the list of filenames
for `org-protocol-the-protocol' and sub-protocols defined in
`org-protocol-protocol-alist' and `org-protocol-protocol-alist-default'.")
(custom-put-if-not 'cwarn 'custom-version "21.1")
(custom-put-if-not 'cwarn 'group-documentation "Highlight suspicious C and C++ constructions.")
(custom-put-if-not 'rst-faces-defaults 'custom-version "21.1")
(custom-put-if-not 'rst-faces-defaults 'group-documentation "Values used to generate default faces for section titles on all levels.
Tweak these if you are content with how section title faces are built in
general but you do not like the details.")
(custom-put-if-not 'iimage 'custom-version "22.1")
(custom-put-if-not 'iimage 'group-documentation "Support for inline images.")
(custom-put-if-not 'pcomplete 'custom-version "21.1")
(custom-put-if-not 'pcomplete 'group-documentation "Programmable completion.")
(custom-put-if-not 'gnus-delay 'custom-version "22.1")
(custom-put-if-not 'gnus-delay 'group-documentation "Arrange for sending postings later.")
(custom-put-if-not 'ps-print-horizontal 'custom-version "20")
(custom-put-if-not 'ps-print-horizontal 'group-documentation "Horizontal page layout.")
(custom-put-if-not 'ps-print-horizontal 'custom-tag "Horizontal")
(custom-put-if-not 'footnote 'custom-version "21.1")
(custom-put-if-not 'footnote 'group-documentation "Support for footnotes in mail and news messages.")
(custom-put-if-not 'bs 'custom-version "21.1")
(custom-put-if-not 'bs 'group-documentation "Buffer Selection: Maintaining buffers by buffer menu.")
(custom-put-if-not 'glasses 'custom-version "21.1")
(custom-put-if-not 'glasses 'group-documentation "Make unreadable code likeThis(one) readable.")
(custom-put-if-not 'python 'custom-version "22.1")
(custom-put-if-not 'python 'group-documentation "Silly walks in the Python language.")
(custom-put-if-not 'ps-print-page 'custom-version "20")
(custom-put-if-not 'ps-print-page 'group-documentation "Page customization.")
(custom-put-if-not 'ps-print-page 'custom-tag "Page")
(custom-put-if-not 'url 'custom-version "22.1")
(custom-put-if-not 'url 'group-documentation "Uniform Resource Locator tool.")
(custom-put-if-not 'postscript 'custom-version "20")
(custom-put-if-not 'postscript 'group-documentation "PostScript Group.")
(custom-put-if-not 'postscript 'custom-tag "PostScript")
(custom-put-if-not 'mailcap 'custom-version "21.1")
(custom-put-if-not 'mailcap 'group-documentation "Definition of viewers for MIME types.")
(custom-put-if-not 'xesam 'custom-version "23.1")
(custom-put-if-not 'xesam 'group-documentation "Xesam compatible interface to search engines.")
(custom-put-if-not 'fortune 'custom-version "21.1")
(custom-put-if-not 'fortune 'group-documentation "Settings for fortune.")
(custom-put-if-not 'cua 'custom-version "22.1")
(custom-put-if-not 'cua 'group-documentation "Emulate CUA key bindings including C-x and C-c.")
(custom-put-if-not 'ebnf-special 'custom-version "20")
(custom-put-if-not 'ebnf-special 'group-documentation "Special customization.")
(custom-put-if-not 'ebnf-special 'custom-tag "Special")
(custom-put-if-not 'savehist 'custom-version "22.1")
(custom-put-if-not 'savehist 'group-documentation "Save minibuffer history.")
(custom-put-if-not 'thumbs 'custom-version "22.1")
(custom-put-if-not 'thumbs 'group-documentation "Thumbnails previewer.")
(custom-put-if-not 'auth-source 'custom-version "23.1")
(custom-put-if-not 'auth-source 'group-documentation "Authentication sources.")
(custom-put-if-not 'net-utils 'custom-version "20.3")
(custom-put-if-not 'net-utils 'group-documentation "Network utility functions.")
(custom-put-if-not 'ps-print-n-up 'custom-version "20")
(custom-put-if-not 'ps-print-n-up 'group-documentation "N-up customization.")
(custom-put-if-not 'ps-print-n-up 'custom-tag "N-Up")
(custom-put-if-not 'package 'custom-version "24.1")
(custom-put-if-not 'package 'group-documentation "Manager for Emacs Lisp packages.")
(custom-put-if-not 'ansi-colors 'custom-version "21.1")
(custom-put-if-not 'ansi-colors 'group-documentation "Translating SGR control sequences to faces.
This translation effectively colorizes strings and regions based upon
SGR control sequences embedded in the text.  SGR (Select Graphic
Rendition) control sequences are defined in section 3.8.117 of the
ECMA-48 standard (identical to ISO/IEC 6429), which is freely available
as a PDF file <URL:http://www.ecma.ch/ecma1/STAND/ECMA-048.HTM>.")
(custom-put-if-not 'whitespace 'custom-version "23.1")
(custom-put-if-not 'whitespace 'group-documentation "Visualize blanks (TAB, (HARD) SPACE and NEWLINE).")

(defvar custom-versions-load-alist '(("20.3.3" "dos-vars") ("19.29" time-stamp) ("20.1" time-stamp) ("22.3" message) ("20.4" files crisp compile hilit-chg sh-script help) ("21.3" gnus-agent sql ange-ftp) ("20.8" sql) ("21.2" mm-util) ("22.2" vc-mtn tls mail-source find-dired vc-hg bibtex-style gnus-sum dired css-mode desktop sql gdb-mi) ("23.2" mm-encode rmail gnus-group gnus-sum help-fns diary-lib dired calendar tramp-gvfs "window" elint minibuffer auth-source bytecomp ansi-color files doc-view lunar desktop comint message rmailmm simple gdb-mi) ("20.3" paren avoid xscheme msb sendmail etags find-func dabbrev compile mouse which-func hexl uce vc "replace" add-log ffap rmail vcursor browse-url simple diary-lib cus-edit debug) ("23.3" diary-lib python desktop rmailsum rmail calendar) ("21.1" paren sb-image strokes dabbrev debug net-utils rmail latin1-disp sgml-mode wid-edit server tooltip gnus-start "window" frame "paths" find-func message ange-ftp hideshow ezimage vc-cvs rmailedit vc "isearch" files faces cal-hebrew browse-url vc-rcs etags flyspell cus-edit gnus-group fortran font-lock add-log sendmail smtpmail ps-print vc-sccs gnus-agent nnmail simple gnus-sum gnus-art cperl-mode) ("24.1" esh-arg em-hist url-cache ange-ftp em-prompt mm-decode comint pcmpl-unix em-banner hl-line appt gnus-srvr ibuffer em-term pop3 em-script auth-source em-cmpl em-alias dired-x etags em-glob em-rebind em-dirs image vc mule mm-view esh-util em-smart em-pred cus-edit vc-git smtpmail vc-sccs smiley gnus-msg shr gnus-art esh-proc gnus-start emacs-lock shell cc-fonts vc-hg gnus-html image-mode esh-var facemenu rmail vc-cvs simple woman em-ls font-lock esh-cmd calendar gnus-group find-dired server saveplace ido f90 copyright "window" jka-cmpr-hook diary-lib url-queue vc-rcs gnus-gravatar python gnus-sum glasses package-x browse-url faces package flyspell info rst mml esh-mode mml2015 message feedmail mouse sendmail esh-io sql rcirc vc-svn log-edit files gnus-util em-unix custom esh-ext js compile gnus) ("22" ps-print ebnf2ps) ("22.1" add-log generic-x bookmark gnus-util gnus-score facemenu minibuffer allout dabbrev sgml-mode fortran sql uudecode ispell landmark gnus-int find-func hi-lock gnus-srvr cal-dst binhex gnus-win sh-script comint mail-extr "paragraphs" shadowfile mouse mule descr-text smime time latin1-disp vc flow-fill calendar hl-line tex-mode glasses info view "replace" "buff-menu" nnmail ielm mml mm-util mml2015 custom locate files cal-tex spam mm-url sendmail rfn-eshadow keypad frame iswitchb mm-view imap warnings vc-svn diary-lib starttls ffap ange-ftp gnus tls faces gnus-cite vc-cvs x-dnd gnus-group gnus-delay make-mode compare-w dnd tcl mm-uu imenu gnus-agent gnus-art diff-mode rmail desktop compile gnus-sum mml-sec gnus-fun grep dired deuglify autorevert gnus-start gdb-mi message gnus-msg cus-edit fringe pop3 server mail-source mm-decode simple gnus-spec) ("20" ps-print ebnf2ps) ("23.1" faces view nnmail checkdoc vc-git select "startup" cus-edit newcomment compile net-utils smiley hideif vc-arch "mule-cmds" fortune f90 "misearch" mml descr-text info face-remap dired-aux gnus-draft bibtex help vc-hooks gnus "replace" gnus-util smime ffap pop3 tls spam-report gnus-dired mm-decode copyright "isearch" allout mm-uu "window" gnus-sum vc-hg calendar holidays gdb-mi minibuffer simple gnus-score informat fortran rmail rmailmm gnus-group server vc-mtn filesets message gnus-msg pcmpl-unix vc-cvs sendmail woman gnus-bookmark browse-url time imap tex-mode gnus-art icomplete files nnmairix))
 "For internal use by custom.")

(provide 'cus-load)
;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; cus-load.el ends here
